---
name: AdvancedRank
version: 1.0.0
api: 4.0.0
main: Zwuiix\AdvancedRank\Main
authors:
- Zwuiix
permissions:
  advancedrank:
    default: op
    description: Allow usage of all AdvancedRank features
  advancedrank.rank.set:
    default: op
    description: Allow to use AdvancedRank (set) command!
  advancedrank.rank.give:
    default: op
    description: Allow to use AdvancedRank (give) command!
  advancedrank.rank.create:
    default: op
    description: Allow to use AdvancedRank (create) command!
  advancedrank.rank.delete:
    default: op
    description: Allow to use AdvancedRank (delete) command!
  advancedrank.rank.addpermission:
    default: op
    description: Allow to use AdvancedRank (addpermission) command!
  advancedrank.rank.removepermission:
    default: op
    description: Allow to use AdvancedRank (removepermission) command!
  advancedrank.rank.list:
    default: op
    description: Allow to use AdvancedRank (list) command!
  advancedrank.rank.info:
    default: op
    description: Allow to use AdvancedRank (info) command!
  advancedrank.rank.user:
    default: op
    description: Allow to use AdvancedRank (user) command!
  advancedrank.rank.manage:
    default: op
    description: Allow to use AdvancedRank (manage) command!
  advancedrank.rank.adduserpermission:
    default: op
    description: Allow to use AdvancedRank (adduserpermission) command!
  advancedrank.rank.removeuserpermission:
    default: op
    description: Allow to use AdvancedRank (removeuserpermission) command!
description: Loaded by FolderPluginLoader
github: https://github.com/Zwuiix-cmd
loader:
  name: FolderPluginLoader
  main: Zwuiix\Main
  version: 1.0.0
  api:
  - 4.0.0
  authors:
  - Zwuiix
  - pmmp
...
