---
name: AdvancedRank
version: 1.0.0
api: 4.0.0
main: Zwuiix\AdvancedRank\Main
authors:
- Zwuiix
permissions:
  advancedrank:
    default: op
    description: Allow usage of all AdvancedStick features
  advancedrank.rank.set:
    default: op
    description: Allow to use AdvancedStick (set) command!
  advancedrank.rank.give:
    default: op
    description: Allow to use AdvancedStick (give) command!
  advancedrank.rank.create:
    default: op
    description: Allow to use AdvancedStick (create) command!
  advancedrank.rank.delete:
    default: op
    description: Allow to use AdvancedStick (delete) command!
  advancedrank.rank.addpermission:
    default: op
    description: Allow to use AdvancedStick (addpermission) command!
  advancedrank.rank.removepermission:
    default: op
    description: Allow to use AdvancedStick (removepermission) command!
  advancedrank.rank.list:
    default: op
    description: Allow to use AdvancedStick (list) command!
  advancedrank.rank.info:
    default: op
    description: Allow to use AdvancedStick (info) command!
  advancedrank.rank.user:
    default: op
    description: Allow to use AdvancedStick (user) command!
  advancedrank.rank.manage:
    default: op
    description: Allow to use AdvancedStick (manage) command!
  advancedrank.rank.adduserpermission:
    default: op
    description: Allow to use AdvancedStick (adduserpermission) command!
  advancedrank.rank.removeuserpermission:
    default: op
    description: Allow to use AdvancedStick (removeuserpermission) command!
  advancedrank.rank.tempgive:
    default: op
    description: Allow to use AdvancedStick (tempgive) command!
description: Loaded by FolderPluginLoader
github: https://github.com/Zwuiix-cmd
loader:
  name: FolderPluginLoader
  main: Zwuiix\Main
  version: 1.0.0
  api:
  - 4.0.0
  authors:
  - Zwuiix
  - pmmp
...
