---
name: AdvancedDiscord
version: 1.0.0
api: 4.0.0
main: Zwuiix\AdvancedDiscord\Main
depend: DiscordBot
authors:
- Zwuiix
description: Loaded by FolderPluginLoader
github: https://github.com/Zwuiix-cmd
loader:
  name: FolderPluginLoader
  main: Zwuiix\Main
  version: 1.0.0
  api:
  - 4.0.0
  authors:
  - Zwuiix
  - pmmp
...
