---
#               _                               _ _____             _
#     /\      | |                             | |  __ \           | |
#    /  \   __| |_   ____ _ _ __   ___ ___  __| | |__) |__ _ _ __ | | __
#   / /\ \ / _` \ \ / / _` | '_ \ / __/ _ \/ _` |  _  // _` | '_ \| |/ /
#  / ____ \ (_| |\ V / (_| | | | | (_|  __/ (_| | | \ \ (_| | | | |   <
# /_/    \_\__,_| \_/ \__,_|_| |_|\___\___|\__,_|_|  \_\__,_|_| |_|_|\_\
#
#

default-rank-type: "json"
default-rank: "Player"

# Activate or deactivate the forms,
# if they are activated you just have to make the command without the arguments,
# a **CustomForm** is created automatically!
form: "true"

# You can add your own language, you just have to create an archive in .ini and respect the name in the lang folder!
langage: "fr"

# Enables or disables the use of the prefix!
use-prefix: "true"

# This allows you to use the {DAYS}-{MINUTE}-{SECOND}
timezone: "Europe/Paris"

extensions:
  EconomyAPI: "false"
  PiggyFactions: "false"
  SimpleFaction: "false"
  FactionMaster: "false"
  InfoTag: "false"
...
